FROM golang:1.15-alpine

RUN go env -w GO111MODULE=on && go env -w GOPROXY=https://goproxy.io,direct
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk add build-base

COPY . /app
WORKDIR /app

CMD sh test_all.sh