version: "3.8"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - 8000:8000
    env_file: .env.docker
#    volumes:
#      - .:/code
#      - logvolume01:/var/log
    links:
      - redis
      - postgres
  redis:
    image: redis:6-alpine
  postgres:
    image: postgres:13-alpine
    environment:
      "POSTGRES_PASSWORD": "defaultPassword"
  test:
    build:
      context: .
      dockerfile: Dockerfile.testing
    ports:
      - 8000:8000
    env_file: .env.docker_test
#    volumes:
#      - ./:/app/
#      - logvolume01:/var/log
    links:
      - redis
      - postgres
# volumes:
#  logvolume01: {}