version: "3.8"  # optional since v1.27.0
services:
  web:
    build: .
#    ports:
#      - 8000:8000
    env_file: .env.docker
#    volumes:
#      - .:/code
#      - logvolume01:/var/log
    links:
      - redis
      - postgres
  redis:
    image: redis:6-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  postgres:
    image: postgres:13-alpine
    environment:
      "POSTGRES_PASSWORD": "defaultPassword"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  test:
    build:
      context: .
      dockerfile: Dockerfile.testing
    ports:
      - 8000:8000
    env_file: .env.docker_test
#    volumes:
#      - ./:/app/
#      - logvolume01:/var/log
    links:
      - redis
      - postgres
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx:alpine
    links:
      - web
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
      # for testing
      - "8181:8081"
      - "8182:8082"
      - "8183:8083"
      - "8184:8084"
# volumes:
#  logvolume01: {}