CREATE TABLE "accounts" ("id" bigserial,"created_at" timestamptz,"updated_at" timestamptz,"deleted_at" timestamptz,"uri" text UNIQUE,"url" text,"type" text,"username" text,"domain" text,"name" text,"summary" text,"public_key" text,"followers_uri" text,"following_uri" text,"inbox_uri" text,"outbox_uri" text,PRIMARY KEY ("id"));
CREATE INDEX "idx_accounts_deleted_at" ON "accounts" ("deleted_at");
CREATE TABLE "communes" ("id" bigserial,"created_at" timestamptz,"updated_at" timestamptz,"deleted_at" timestamptz,"uri" text UNIQUE,"url" text,"type" text,"username" text,"domain" text,"name" text,"summary" text,"public_key" text,"followers_uri" text,"following_uri" text,"inbox_uri" text,"outbox_uri" text,PRIMARY KEY ("id"));
CREATE INDEX "idx_communes_deleted_at" ON "communes" ("deleted_at");
CREATE TABLE "commune_members" ("commune_id" bigint,"account_id" bigint,"created_at" timestamptz,"role" text,PRIMARY KEY ("commune_id","account_id"),CONSTRAINT "fk_commune_members_account" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"),CONSTRAINT "fk_commune_members_commune" FOREIGN KEY ("commune_id") REFERENCES "communes"("id"));
CREATE TABLE "users" ("account_id" bigserial,"email" text,"encrypted_password" text,"private_key" text,"is_verified" boolean,"is_admin" boolean,"is_moderator" boolean,PRIMARY KEY ("account_id"),CONSTRAINT "fk_users_account" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "local_communes" ("commune_id" bigserial,"private_key" text,"is_verified" boolean,PRIMARY KEY ("commune_id"),CONSTRAINT "fk_local_communes_commune" FOREIGN KEY ("commune_id") REFERENCES "communes"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "categories" ("id" bigserial,"created_at" timestamptz,"updated_at" timestamptz,"deleted_at" timestamptz,"uri" text UNIQUE,"url" text,"type" text,"commune_id" bigint,"slug" text,PRIMARY KEY ("id"),CONSTRAINT "fk_communes_categories" FOREIGN KEY ("commune_id") REFERENCES "communes"("id"),CONSTRAINT "fk_categories_commune" FOREIGN KEY ("commune_id") REFERENCES "communes"("id"));
CREATE INDEX "idx_categories_deleted_at" ON "categories" ("deleted_at");
CREATE TABLE "posts" ("id" bigserial,"created_at" timestamptz,"updated_at" timestamptz,"deleted_at" timestamptz,"uri" text UNIQUE,"url" text,"type" text,"author_id" bigint,"category_id" bigint,"content" text,"media_type" text,"source" text,"source_media_type" text,"name" text,"reply_to_id" bigint,PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_posts" FOREIGN KEY ("author_id") REFERENCES "accounts"("id"),CONSTRAINT "fk_posts_author" FOREIGN KEY ("author_id") REFERENCES "accounts"("id"),CONSTRAINT "fk_categories_posts" FOREIGN KEY ("category_id") REFERENCES "categories"("id"),CONSTRAINT "fk_posts_category" FOREIGN KEY ("category_id") REFERENCES "categories"("id"),CONSTRAINT "fk_posts_reply_to" FOREIGN KEY ("reply_to_id") REFERENCES "posts"("id"));
CREATE INDEX "idx_posts_deleted_at" ON "posts" ("deleted_at")