# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.15

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:alpine
      - image: circleci/redis:alpine 

    environment:
      DATABASE_URL: "postgres://postgres:defaultPassword@postgres/commune_go_test"
      COMMUNE_LOCAL_DOMAINS: "commune1.localdomain commune2.localdomain commune3.localdomain commune4.localdomain commune1.misaka4e21.science commune2.misaka4e21.science"
      REDIS_ADDR: "redis:6379"
    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: ~/commune
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: bash do_all_tests.sh
